# Generated by Django 2.1.5 on 2019-01-31 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_auto_20190131_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='numero',
            field=models.CharField(max_length=10),
        ),
    ]
